#!/bin/bash

# Get the current desktop session
current_session=$XDG_CURRENT_DESKTOP

# Define the function for setting wallpapers in Hyprland
set_wallpaper_hyprland() {
	dir="${HOME}/.config/hypr/Wallpapers"
	BG="$(find "$dir" -name '*.jpg' -o -name '*.png' -o -name "*.mp4" | shuf -n1)"
	PROGRAM="swww-daemon"
	trans_type="random"

  swww img "$BG" --transition-fps 255 --transition-type $trans_type --transition-duration 1
}

# Define the function for setting wallpapers in other sessions
set_wallpaper_other() {
	dir="${HOME}/.local/share/walls"
	BG="$(find "$dir" -name '*.jpg' -o -name '*.png' | shuf -n1)"
	cat "$BG" > ~/.local/share/walls/wallpaper.jpg
	xwallpaper --zoom "$BG"
}

# Check the current session and run the appropriate function
case "$current_session" in
"Hyprland")
	set_wallpaper_hyprland
	;;
*)
	set_wallpaper_other
	;;
esac

# Sleep for 10 minutes before calling the script again
sleep 10m

# Call the script again to set wallpaper
exec "$0"
