[pyprland]
plugins = [
	"scratchpads"
]

[scratchpads.term]
command   = "foot -a foot-popterm"
animation = "fromTop"
position  = ""
margin	  = "20%"
class	  = "foot-popterm"
size	  = "60% 60%"
max_size  = "1920px 100%"
lazy	  = true

[scratchpads.qalc]
command   = "foot -a qalc-popterm -e qalc -s 'autocalc 1'"
animation = "fromTop"
position  = ""
margin	  = "20%"
class	  = "qalc-popterm"
size	  = "40% 60%"
max_size  = "1920px 100%"
lazy	  = true

[scratchpads.workspaces]
command   = ""   # no command needed, window already exists
animation = "fromTop"
position  = ""
margin    = "0%"
class     = "Workspacesclient"
size      = "100% 100%"
max_size  = "1920px 1080px"
lazy      = true

