[pyprland]
plugins = [
	"scratchpads"
]

[scratchpads.term]
command   = "foot -a foot-popterm"
animation = "fromTop"
position  = ""
margin	  = "20%"
class	  = "foot-popterm"
size	  = "60% 60%"
max_size  = "1920px 100%"
lazy	  = true

[scratchpads.qalc]
command   = "foot -a qalc-popterm -e qalc -s "autocalc 1"
animation = "fromTop"
position  = ""
margin	  = "20%"
class	  = "qalc-popterm"
size	  = "40% 60%"
max_size  = "1920px 100%"
lazy	  = true
