[pyprland]
plugins = [
	"scratchpads"
]

[scratchpads.term]
command   = "foot -a foot-popterm"
animation = "fromTop"
size      = "60% 60%"
position  = "20% 20%"
max_size  = "1920px 100%"
lazy      = true

[scratchpads.qalc]
command   = "foot -a qalc-popterm -e qalc -s 'autocalc 1'"
animation = "fromTop"
margin	  = 20
size      = "40% 60%"
position  = "30% 20%"
max_size  = "1920px 100%"
lazy      = true

[scratchpads.workspaces]
command   = ""   # no command needed, window already exists
animation = ""
position  = ""
alt_toggle= "true"
margin    = 0
class     = "Workspacesclient"
size      = "100% 100%"
max_size  = "1920px 1080px"
lazy      = true
